import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import { OtpExpiredError, OtpInvalidError, RateLimitError } from "./auth-errors";

type OtpRecord = { phone: string; hash: string; expiresAt: number; resendAt: number; attempts: number; maxAttempts: number; provider: string };
const store = new Map<string, OtpRecord>();
export const OTP_COOKIE_NAME = "arogga_otp_challenge";
export function getOtpConfig() { return { provider: process.env.OTP_PROVIDER || "demo", demoCode: process.env.OTP_DEMO_CODE || "123456", expiresSeconds: Number(process.env.OTP_EXPIRES_SECONDS || 300), resendSeconds: Number(process.env.OTP_RESEND_SECONDS || 60), maxAttempts: Number(process.env.OTP_MAX_ATTEMPTS || 5) }; }
export function hashOtp(otp: string, phone: string) { return createHash("sha256").update(`${phone}:${otp}:${process.env.AUTH_SESSION_SECRET || "local-dev-secret"}`).digest("hex"); }
function safeEqual(a: string, b: string) { const left = Buffer.from(a); const right = Buffer.from(b); return left.length === right.length && timingSafeEqual(left, right); }
export function createOtpChallenge(phone: string) { const cfg = getOtpConfig(); const otp = cfg.provider === "demo" ? cfg.demoCode : randomBytes(3).toString("hex").slice(0, 6).padStart(6, "0"); const id = randomBytes(16).toString("base64url"); const now = Date.now(); store.set(id, { phone, hash: hashOtp(otp, phone), expiresAt: now + cfg.expiresSeconds * 1000, resendAt: now + cfg.resendSeconds * 1000, attempts: 0, maxAttempts: cfg.maxAttempts, provider: cfg.provider }); return { challengeId: id, phone, expiresInSeconds: cfg.expiresSeconds, resendInSeconds: cfg.resendSeconds, maxAttempts: cfg.maxAttempts, demoOtp: process.env.NODE_ENV === "production" ? undefined : cfg.provider === "demo" ? otp : undefined }; }
export function assertCanResend(challengeId?: string) { if (!challengeId) return; const record = store.get(challengeId); if (!record) return; if (Date.now() < record.resendAt) throw new RateLimitError(`Please wait ${Math.ceil((record.resendAt - Date.now()) / 1000)}s before requesting another OTP.`); }
export function verifyOtpChallenge(challengeId: string | undefined, phone: string, otp: string) { const record = challengeId ? store.get(challengeId) : null; if (!record || record.phone !== phone) throw new OtpInvalidError("OTP session not found. Please request a new code."); if (Date.now() > record.expiresAt) { store.delete(challengeId!); throw new OtpExpiredError(); } if (record.attempts >= record.maxAttempts) throw new OtpInvalidError("Maximum verification attempts exceeded. Please request a new OTP."); record.attempts += 1; if (!safeEqual(record.hash, hashOtp(otp, phone))) throw new OtpInvalidError(`Invalid OTP. ${process.env.NODE_ENV === "production" ? "" : "Use the development demo code."}`.trim()); store.delete(challengeId!); return true; }
export function resetOtpStoreForTests() { store.clear(); }
