"use client";

import { ProductSectionCollection } from "@/Components/HomeComponents/ProductSection";

const STORE_PRODUCT_ROWS = [
  {
    id: "supplement-festival",
    title: "Supplement Festival",
    subtitle: "Daily nutrition, vitamins, minerals and wellness essentials",
    href: "/store?section=supplement-festival",
    minimumCards: 20,
    startIndex: 0,
    background: "linear-gradient(145deg, #f3fff9 0%, #e9fbf2 100%)",
    headingColor: "#087b55",
  },
  {
    id: "best-selling",
    title: "Best Selling",
    subtitle: "Popular products customers choose again and again",
    href: "/store?section=best-selling",
    minimumCards: 20,
    startIndex: 20,
    background: "linear-gradient(145deg, #fffaf0 0%, #fff2d8 100%)",
    headingColor: "#a86100",
  },
  {
    id: "beauty-personal-care",
    title: "Beauty & Personal Care",
    subtitle: "Skincare, haircare and beauty favourites for every routine",
    href: "/store?section=beauty-personal-care",
    minimumCards: 20,
    startIndex: 40,
    background: "linear-gradient(145deg, #fff7fb 0%, #ffeaf3 100%)",
    headingColor: "#ad255a",
  },
  {
    id: "health-wellness",
    title: "Health & Wellness",
    subtitle: "Everyday healthcare and wellness support for the whole family",
    href: "/store?section=health-wellness",
    minimumCards: 20,
    startIndex: 60,
    background: "linear-gradient(145deg, #f7f5ff 0%, #eee9ff 100%)",
    headingColor: "#6941c6",
  },
  {
    id: "keep-it-luxe",
    title: "Keep It Luxe",
    subtitle: "Premium picks that make everyday care feel extraordinary",
    href: "/store?section=keep-it-luxe",
    minimumCards: 20,
    startIndex: 80,
    background: "linear-gradient(145deg, #fffdf4 0%, #f8edcb 100%)",
    headingColor: "#8b6517",
  },
  {
    id: "otc-medicine",
    title: "OTC Medicine",
    subtitle: "Trusted over-the-counter essentials for common health needs",
    href: "/store?section=otc-medicine",
    minimumCards: 20,
    startIndex: 100,
    background: "linear-gradient(145deg, #f5fbff 0%, #e8f5ff 100%)",
    headingColor: "#175cd3",
  },
  {
    id: "sun-splash",
    title: "Sun & Splash",
    subtitle: "Sun care, hydration and refreshing seasonal favourites",
    href: "/store?section=sun-splash",
    minimumCards: 20,
    startIndex: 120,
    background: "linear-gradient(145deg, #fffdf1 0%, #fff3bd 100%)",
    headingColor: "#b54708",
  },
  {
    id: "baby-care-hub",
    title: "Baby Care Hub",
    subtitle: "Gentle essentials for babies, toddlers and caring parents",
    href: "/store?section=baby-care-hub",
    minimumCards: 20,
    startIndex: 140,
    background: "linear-gradient(145deg, #f8fbff 0%, #eaf3ff 100%)",
    headingColor: "#3563a9",
  },
  {
    id: "crave-cart",
    title: "Crave Cart",
    subtitle: "Tasty snacks, pantry favourites and everyday food essentials",
    href: "/store?section=crave-cart",
    minimumCards: 20,
    startIndex: 160,
    background: "linear-gradient(145deg, #fff9f2 0%, #ffe9d2 100%)",
    headingColor: "#c2410c",
  },
  {
    id: "fresh-clean-days",
    title: "Fresh & Clean Days",
    subtitle: "Home, hygiene and cleaning essentials for a fresher routine",
    href: "/store?section=fresh-clean-days",
    minimumCards: 20,
    startIndex: 180,
    background: "linear-gradient(145deg, #f4fcff 0%, #e2f7fb 100%)",
    headingColor: "#0e7490",
  },
  {
    id: "your-pets-best",
    title: "Your Pet's Best",
    subtitle: "Food, grooming and care products for happier pets",
    href: "/store?section=your-pets-best",
    minimumCards: 20,
    startIndex: 200,
    background: "linear-gradient(145deg, #f9fff3 0%, #ebf9d8 100%)",
    headingColor: "#4d7c0f",
  },
  {
    id: "turn-up-the-heat",
    title: "Turn Up the Heat 🔥",
    subtitle: "Hot deals and bold picks selected for maximum value",
    href: "/store?section=turn-up-the-heat",
    minimumCards: 20,
    startIndex: 220,
    background: "linear-gradient(145deg, #fff5f3 0%, #ffe1dc 100%)",
    headingColor: "#d92d20",
  },
  {
    id: "feel-fit-fine",
    title: "Feel. Fit. Fine.",
    subtitle: "Fitness, recovery and lifestyle products for active days",
    href: "/store?section=feel-fit-fine",
    minimumCards: 20,
    startIndex: 240,
    background: "linear-gradient(145deg, #f4fbf8 0%, #e1f5ec 100%)",
    headingColor: "#067647",
  },
  {
    id: "anti-bacterial-vet-care",
    title: "Anti-Bacterial Vet Care",
    subtitle: "Specialised hygiene and antibacterial care for animals",
    href: "/store?section=anti-bacterial-vet-care",
    minimumCards: 20,
    startIndex: 260,
    background: "linear-gradient(145deg, #f8f8ff 0%, #ececff 100%)",
    headingColor: "#4e5ba6",
  },
] as const;

export default function StoreProductSections() {
  return <ProductSectionCollection sections={[...STORE_PRODUCT_ROWS]} />;
}
