export const ORDER_STATUSES = ["Pending", "Confirmed", "Processing", "Packed", "Shipped", "Out for Delivery", "Delivered", "Cancelled", "Return Requested", "Returned", "Refunded", "Failed"] as const;
export type LocalOrderStatus = typeof ORDER_STATUSES[number];
export type LocalOrder = { id: string; orderNumber: string; ownerPhone: string; status: LocalOrderStatus; paymentStatus: "Pending" | "Paid" | "Failed" | "Refunded"; paymentMethod: string; deliveryMethod: string; address: unknown; items: unknown[]; totals: { subtotal: number; discount: number; vat: number; shipping: number; grandTotal: number }; idempotencyKey: string; createdAt: string; updatedAt: string; trackingEvents: Array<{ id: string; title: string; createdAt: string }>; invoice: { invoiceNumber: string; total: number; issuedAt: string }; cancellationReason?: string; returnRequestId?: string };
type CreateInput = { ownerPhone: string; address: unknown; items: unknown[]; totals: LocalOrder["totals"]; paymentMethod: string; deliveryMethod: string; idempotencyKey: string };
function now() { return new Date().toISOString(); }
export function createTrackingEvents(status: LocalOrderStatus) { return [{ id: `track-${Date.now()}`, title: status, createdAt: now() }]; }
export function createInvoiceModel(orderId: string, total: number) { return { invoiceNumber: `INV-${orderId}`, total, issuedAt: now() }; }
export function createLocalOrder(existing: LocalOrder[], input: CreateInput) { if (!input.ownerPhone) throw new Error("Authenticated session required"); if (!input.items.length) throw new Error("Cart is empty"); const duplicate = existing.find((o) => o.ownerPhone === input.ownerPhone && o.idempotencyKey === input.idempotencyKey); if (duplicate) return { order: duplicate, orders: existing }; const id = `ord-${Date.now()}-${Math.random().toString(16).slice(2, 8)}`; const order: LocalOrder = { id, orderNumber: `ARG-${Date.now()}`, ownerPhone: input.ownerPhone, status: "Pending", paymentStatus: input.paymentMethod === "Cash on Delivery" ? "Pending" : "Paid", paymentMethod: input.paymentMethod, deliveryMethod: input.deliveryMethod, address: input.address, items: input.items, totals: input.totals, idempotencyKey: input.idempotencyKey, createdAt: now(), updatedAt: now(), trackingEvents: createTrackingEvents("Pending"), invoice: createInvoiceModel(id, input.totals.grandTotal) }; return { order, orders: [order, ...existing] }; }
export function listOrders(orders: LocalOrder[], ownerPhone: string) { return orders.filter((o) => o.ownerPhone === ownerPhone); }
export function findOwnedOrder(orders: LocalOrder[], orderId: string, ownerPhone: string) { return orders.find((o) => o.id === orderId && o.ownerPhone === ownerPhone) || null; }
export function cancelOrder(orders: LocalOrder[], orderId: string, ownerPhone: string, reason: string) { const order = findOwnedOrder(orders, orderId, ownerPhone); if (!order) throw new Error("Order not found"); if (["Delivered", "Cancelled", "Return Requested", "Returned", "Refunded"].includes(order.status)) throw new Error("Order cannot be cancelled"); const next = { ...order, status: "Cancelled" as const, cancellationReason: reason, updatedAt: now(), trackingEvents: [...order.trackingEvents, ...createTrackingEvents("Cancelled")] }; return { order: next, orders: orders.map((o) => o.id === orderId ? next : o) }; }
export function requestReturnOrder(orders: LocalOrder[], orderId: string, ownerPhone: string) { const order = findOwnedOrder(orders, orderId, ownerPhone); if (!order) throw new Error("Order not found"); if (order.status !== "Delivered") throw new Error("Only delivered orders can be returned"); const next = { ...order, status: "Return Requested" as const, returnRequestId: `RET-${Date.now()}`, updatedAt: now(), trackingEvents: [...order.trackingEvents, ...createTrackingEvents("Return Requested")] }; return { order: next, orders: orders.map((o) => o.id === orderId ? next : o) }; }
export function reorder(orders: LocalOrder[], orderId: string, ownerPhone: string) { const order = findOwnedOrder(orders, orderId, ownerPhone); if (!order) throw new Error("Order not found"); return order.items; }
