"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import Image from "next/image";
import { Search, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import styles from "./SearchBar.module.css";
type Result={id:string;slug:string;name:string;brand:string;category:string;price:number;currency:string;image:string;href:string};
export default function SearchBar({compact=false}:{compact?:boolean}){const router=useRouter();const [query,setQuery]=useState("");const [results,setResults]=useState<Result[]>([]);const [open,setOpen]=useState(false);const [loading,setLoading]=useState(false);const wrap=useRef<HTMLDivElement>(null);useEffect(()=>{const onDown=(e:MouseEvent)=>{if(wrap.current&&!wrap.current.contains(e.target as Node))setOpen(false)};document.addEventListener("mousedown",onDown);return()=>document.removeEventListener("mousedown",onDown)},[]);useEffect(()=>{const q=query.trim();if(q.length<2){setResults([]);setLoading(false);return}const controller=new AbortController();const timer=setTimeout(async()=>{setLoading(true);try{const response=await fetch(`/api/products/search?q=${encodeURIComponent(q)}&limit=8`,{signal:controller.signal});const data=await response.json();setResults(Array.isArray(data.results)?data.results:[]);setOpen(true)}catch(e){if(!(e instanceof DOMException&&e.name==="AbortError"))setResults([])}finally{setLoading(false)}},220);return()=>{clearTimeout(timer);controller.abort()}},[query]);function submit(e:React.FormEvent){e.preventDefault();const q=query.trim();if(!q)return;setOpen(false);router.push(`/search?q=${encodeURIComponent(q)}`)}return <div ref={wrap} className={`${styles.wrap} ${compact?styles.compact:""}`}><form onSubmit={submit} className={styles.form}><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} onFocus={()=>query.trim().length>=2&&setOpen(true)} placeholder='Search "Products"' aria-label="Search products"/>{query&&<button type="button" className={styles.clear} onClick={()=>{setQuery("");setResults([])}}><X size={16}/></button>}<button type="submit" className={styles.submit}>Search</button></form>{open&&<div className={styles.panel}><header><strong>{loading?"Searching...":"Search results"}</strong><span>{results.length} found</span></header>{!loading&&results.length===0?<div className={styles.empty}>No matching products found.</div>:results.map(item=><button key={item.id} onClick={()=>{setOpen(false);router.push(item.href)}}><span className={styles.thumb}>{item.image&&<Image src={item.image} alt="" fill sizes="48px" unoptimized/>}</span><span className={styles.content}><strong>{item.name}</strong><small>{item.brand} · {item.category}</small></span><b>৳{item.price.toFixed(2)}</b></button>)}</div>}</div>}
